export { default as Navbar} from "./Navbar"
export { default as Contact} from "./Contact"
export { default as Hero} from "./Hero"
export { default as Project} from "./Project"
export { default as Aboutme} from "./Aboutme"